# Generated by Django 4.2.20 on 2025-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("total_star", models.IntegerField(default=0)),
                ("star_number", models.IntegerField(default=0)),
                ("category", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("cover", models.URLField()),
                ("images", models.JSONField()),
                ("short_title", models.CharField(max_length=255)),
                ("short_desc", models.CharField(max_length=255)),
                ("delivery_time", models.IntegerField()),
                ("revision", models.IntegerField()),
                ("features", models.JSONField()),
                ("sales", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
