# Generated by Django 4.2.20 on 2025-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("seller_id", models.CharField(max_length=255)),
                ("buyer_id", models.CharField(max_length=255)),
                ("buyer_name", models.CharField(max_length=255)),
                ("seller_name", models.CharField(max_length=255)),
                ("read_by_seller", models.BooleanField()),
                ("read_by_buyer", models.BooleanField()),
                ("last_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
